### ISSUE TITLE
All install process OK but white page after install

### ISSUE THREAD

**Issue by RememberForgottenHits** [poppabear8883/UNIT3D-INSTALLER#53]
First of all, we apologize for the my bad English, using translator to write.
 
After several repeated reinstallations and new installations, i got it installed without any problems
. Now when I open the address https://omade.link i see a white page. 

my ping test
--- www.omade.link ping statistics ---
81 packets transmitted, 81 received, 0% packet loss, time 177ms
rtt min/avg/max/mdev = 42.838/47.606/73.914/4.265 ms

How i can fix it and see own new web?

Fresh install ubuntu 18.04

**Comment by RememberForgottenHits** [comment]
/var/log/nginx/error.log

2020/04/09 09:25:30 [error] 13908#13908: *161 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError()
#1 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket()
#2 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer()
#3 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection->connect()
#5 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->conn...PHP message: PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError()
#1 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket()
#2 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer()
#3 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection->connect()
#5 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection

**Comment by RememberForgottenHits** [comment]
Problem solved! The problem was the redis server config files.

Need change row 69
`bind 127.0.0.1 ::1` to `bind 127.0.0.1`

and row 147 to `supervised systemd`

after this run command line

sudo systemctl restart redis.service

And all works fine now!
